[package]
name = "kessels"
version = "1.0.0"
authors = ["miguelraz <miguelraz@ciencias.unam.mx>"]
edition = "2018"

[dependencies]
kessels = { path = "." }
#kessels = { path = "." }

#[dependencies]
#rayon = "1.2.0"
#num = "0.2.0"
